/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.notificationbanner;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiConvert;

import android.app.Activity;
import android.view.View;

import com.tapadoo.alerter.Alerter;

@Kroll.module(name="TitaniumNotificationBanner", id="ti.notificationbanner")
public class TitaniumNotificationBannerModule extends KrollModule
{
	private static final String LCAT = "TitaniumNotificationBannerModule";
	private static final boolean DBG = TiConfig.LOGD;

	// Methods

	@Kroll.method
	public void show(KrollDict args)
	{
		Activity currentActivity = TiApplication.getAppCurrentActivity();
		int duration = args.getInt("duration");
		String title = args.optString("title", "");
		String subtitle = args.optString("subtitle", "");
		String bgColor = args.optString("backgroundColor", "");

		final KrollFunction callback = (KrollFunction) args.get("onClick");

		if (currentActivity == null) {
			Log.e(LCAT, "Cannot option current activity. Try calling this method after your window is opened");
			return;
		}

		Alerter alerter = Alerter.create(currentActivity)
			.setTitle(title)
			.setText(subtitle)
			.setOnClickListener(new View.OnClickListener() {
				@Override
				public void onClick(View view) {
					KrollDict dict = new KrollDict();
					callback.call(getKrollObject(), dict);
				}
			});

		if (duration > 0) {
			alerter.setDuration(duration * 1000);
		}

		if (bgColor != "") {
			int backgroundColor = TiConvert.toColor(bgColor);
			alerter.setBackgroundColorInt(backgroundColor);
		}

		alerter.show();
	}

	@Kroll.method
	public void hide() {
		Alerter.hide();
	}
}
