/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.notificationbanner;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiConvert;

import android.app.Activity;
import android.support.design.widget.Snackbar;
import android.view.View;
import android.support.design.widget.CoordinatorLayout;
import android.view.ViewGroup;

import com.tapadoo.alerter.Alerter;

@Kroll.module(name="TitaniumNotificationBanner", id="ti.notificationbanner")
public class TitaniumNotificationBannerModule extends KrollModule
{
	private static final String LCAT = "TitaniumNotificationBannerModule";
	private static final boolean DBG = TiConfig.LOGD;

	// Methods

	@Kroll.method
	public void show(KrollDict args)
	{
		Activity currentActivity = TiApplication.getAppCurrentActivity();
		int duration = args.getInt("duration");
		String title = args.getString("title");
		String subtitle = args.getString("subtitle");
		
		if (subtitle == null) {
			subtitle = "";
		}
		
		int color = TiConvert.toColor(args.getString("backgroundColor"));

		final KrollFunction callback = (KrollFunction) args.get("onClick");

		if (currentActivity == null) {
			Log.e(LCAT, "Cannot option current activity. Try calling this method after your window is opened");
			return;
		}

		Alerter.create(currentActivity)
			.setTitle(title)
			.setText(subtitle)
			.setDuration(duration*1000) //iOS parity. Alerter expects miliseconds
			.setBackgroundColorInt(color)
			.setOnClickListener(new View.OnClickListener() {
				@Override
				public void onClick(View view) {
					KrollDict dict = new KrollDict();
					callback.call(getKrollObject(), dict);
				}
			})
			.show();
	}

	@Kroll.method
	public void hide() {
		Alerter.hide();
	} 
}

