/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.notificationbanner;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.util.TiConvert;

import android.app.Activity;
import android.support.design.widget.Snackbar;
import android.view.View;

@Kroll.module(name="TitaniumNotificationBanner", id="ti.notificationbanner")
public class TitaniumNotificationBannerModule extends KrollModule
{
	private static final String LCAT = "TitaniumNotificationBannerModule";
	private static final boolean DBG = TiConfig.LOGD;

	// Methods

	@Kroll.method
	public void show(KrollDict args)
	{
		Activity currentActivity = TiApplication.getAppCurrentActivity();

		if (currentActivity == null) {
			Log.e(LCAT, "Activity is null");
			return;
		}

		View view = currentActivity.getWindow().getDecorView().getRootView();

		if (view == null) {
			Log.e(LCAT, "Root view of activity is null");
			return;
		}

		int duration = args.getInt("duration");
		String title = args.getString("title");
		int color = TiConvert.toColor(args.getString("color"));
		String action = args.getString("action") != null ? args.getString("action") : "OK";

		final Snackbar snackbar = Snackbar.make(view, title, duration);
		snackbar.setAction(action, new View.OnClickListener() {
			@Override
			public void onClick(View v) {
				snackbar.dismiss();
			}
		});
		if (color != -1) {
			snackbar.setActionTextColor(color);
		}
		snackbar.show();
	}
}

